### ISSUE TITLE
PyPI missing library dataclasses

### ISSUE THREAD

**Issue by Jay-Jay-D** [Honno/coinflip#44]
I found an issue installing the library with PyPI, seemingly the `dataclasses` library is missing. 

Below the output of the installation, the error and the start of the running after manually installing the `dataclasses` library.

```console
(base) me@my-host:~$ pip install coinflip
Collecting coinflip
  Downloading coinflip-0.0.1-py2.py3-none-any.whl (38 kB)
Collecting python-slugify
  Downloading python-slugify-4.0.1.tar.gz (11 kB)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.6/site-packages (from coinflip) (1.1.1)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.6/site-packages (from coinflip) (1.5.2)
Collecting tabulate
  Downloading tabulate-0.8.7-py3-none-any.whl (24 kB)
Requirement already satisfied: click in ./anaconda3/lib/python3.6/site-packages (from coinflip) (7.1.2)
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: matplotlib in ./anaconda3/lib/python3.6/site-packages (from coinflip) (3.2.2)
Requirement already satisfied: colorama in ./anaconda3/lib/python3.6/site-packages (from coinflip) (0.4.3)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.6/site-packages (from coinflip) (1.19.1)
Collecting text-unidecode>=1.3
  Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 2.5 MB/s 
Requirement already satisfied: pytz>=2017.2 in ./anaconda3/lib/python3.6/site-packages (from pandas->coinflip) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in ./anaconda3/lib/python3.6/site-packages (from pandas->coinflip) (2.8.1)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.6/site-packages (from matplotlib->coinflip) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda3/lib/python3.6/site-packages (from matplotlib->coinflip) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.6/site-packages (from matplotlib->coinflip) (1.2.0)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas->coinflip) (1.15.0)
Building wheels for collected packages: python-slugify
  Building wheel for python-slugify (setup.py) ... done
  Created wheel for python-slugify: filename=python_slugify-4.0.1-py2.py3-none-any.whl size=6769 sha256=3ca8cb4101d29e7847a9725768492591016b517c95bf7ad1f358b3d3e171256b
  Stored in directory: /home/jjd/.cache/pip/wheels/72/e6/db/122611605e60148f54ee2abaca98b2bbeafc6e22486a867bad
Successfully built python-slugify
Installing collected packages: text-unidecode, python-slugify, tabulate, appdirs, coinflip
Successfully installed appdirs-1.4.4 coinflip-0.0.1 python-slugify-4.0.1 tabulate-0.8.7 text-unidecode-1.3
(base) me@my-host:~$ coinflip example-run
Traceback (most recent call last):
  File "/home/jjd/anaconda3/bin/coinflip", line 5, in <module>
    from coinflip.cli import main
  File "/home/jjd/anaconda3/lib/python3.6/site-packages/coinflip/cli.py", line 17, in <module>
    from coinflip.randtests import __all__ as randtest_names
  File "/home/jjd/anaconda3/lib/python3.6/site-packages/coinflip/randtests/__init__.py", line 39, in <module>
    from coinflip.randtests.fourier import discrete_fourier_transform
  File "/home/jjd/anaconda3/lib/python3.6/site-packages/coinflip/randtests/fourier.py", line 1, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
(base) me@my-host:~$ pip install dataclasses
Collecting dataclasses
  Downloading dataclasses-0.7-py3-none-any.whl (18 kB)
Installing collected packages: dataclasses
Successfully installed dataclasses-0.7
(base) me@my-host:~$ coinflip example-run
  +--------------------------------------------------------------------------+  

```

**Comment by Honno** [comment]
Ahh unfortunately coinflip doesn't support py3.6 and below because of this ([dataclasses](https://docs.python.org/3/library/dataclasses.html) is a standard library module that was introduced in 3.7). You'll have to upgrade to a higher Python version to install it without it breaking :( 

The dataclasses module you downloaded in PyPI is a backport I believe, but there's other features in 3.7+ that I use in coinflip too (some of which I do already backport). My idea is to finish coinflip's own testing suite so that it has high coverage, and then I can more easily test if backporting features will not break things—hopefully in the future coinflip will support 3.6!

You've actually found me another problem in that PyPI gave you an older download (version 0.0.1) haha. I think maybe PyPI assumed that old version would work with your Python version? Anywho, I've removed all of those "alpha" releases from PyPI now.
